### ISSUE TITLE
Inline code feature

### ISSUE THREAD

**Issue by phpcoder** [pyrsmk/toast#15]
Hello,
after a couple of years your project is still very useful. For simple application it has a tiny size and it is a big advantage. It is useful for both, js and css. Updating a project would be appreciated by your users.

It is not covered in your docs but perhaps a useful feature. It is possible to include as parameters an inline code instead of a path to a resource. It can be used for a dependency code that is small enough to be included inline.
For example

<pre>
toast(
	'[css]https://fonts.googleapis.com/css?family=.....',
	'../css/bootstrap.min.css',
	'../css/styles.min.css',
	'js/jquery-2.0.0.min.js',

	function() {},
	'js/bootstrap.min.js',

	function() {},
	'js/app.min.js',

	function() {},
	'[js]https://www.googletagmanager.com/gtag/js?id=UA-.....',

	function() {
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());
		gtag('config', 'UA-.....');
	}
);
</pre>

Could you please confirm that it is a proper use of toast v2, and there is no any hidden problems. Thanks again for your nice code.

**Comment by pyrsmk** [comment]
Thanks for your appreciation!

It is indeed a proper use of the library. Each function is executed after each previous file has been downloaded.

FYI, I had planned to upgrade toast to a new version, in a try to a have a smaller footprint, a more elegant syntax, and also to drop IE8 support. I surely can push that ticket in my top list ;)

**Comment by phpcoder** [comment]
Great news. Thanks a lot for continuing your effort. I am sure the project will gain more popularity.
Cheers.

**Comment by pyrsmk** [comment]
Hi,

Great news, the development of the v3 has been advanced!

Here's the stable future syntax, based on your previous example : 

```js
Promise.all([
    toast.css('https://fonts.googleapis.com/css?family=...'),
    toast.load([
        '../css/bootstrap.min.css',
        '../css/styles.min.css',
        'js/jquery-2.0.0.min.js',
    ]),
]).then(function () {
    toast.js(
        [
            'js/bootstrap.min.js',
            'js/app.min.js',
            'https://www.googletagmanager.com/gtag/js?id=UA-...',
        ],
        {
            async: false,
        }
    ).then(function () {
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());
        gtag('config', 'UA-...');
    });
});
```

Keep in touch !

**Comment by ciganox** [comment]
I use 'toast' and I find it very good

**Comment by phpcoder** [comment]
Thank you for a new release.
Perhaps the style now is more clean, even the footprint is slightly larger - 1.8K vs 1.2K minified.

**Comment by pyrsmk** [comment]
Yes, toast v3 will be a bit larger than the v2 because I've added support for LINK/SCRIPT nodes. But I don't really know if I'll keep or throw away this feature as it does not seem to have many use cases (or just very specific ones).

Otherwise, without this feature, I think toast should weigh about 0.8k.

What are your thoughts about this ?

**Comment by phpcoder** [comment]
Honestly, I can't imagine the use of such a feature... However, the size difference is not huge. Maybe create 2 builds, with and without node support? In your v3 syntax example all look nice and all what I can think of is present. BTW, after migration to TS, any size difference was noticed in the final code?

**Comment by pyrsmk** [comment]
Having two builds would be complicated to maintain because node support changes the interface of CSS/JS loaders. Anyway, I think I won't support node loading at all, it will be simpler.

Migration to TS does not really change the size of the build. It even increases it a bit because all of the code tends to become classes with interfaces. But, in the case of toast, the size is smaller especially because :

- the code is cleaner
- IE8 support has been dropped
- the API has been simplified

**Comment by pyrsmk** [comment]
@phpcoder It took some time but Toast v3 is finally out!

**Comment by maPer77** [comment]
Thanks
